# Generated by Django 3.1.2 on 2020-11-07 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={},
        ),
        migrations.RemoveField(
            model_name='events',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='events',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='events',
            name='start_time',
        ),
        migrations.AddField(
            model_name='events',
            name='event',
            field=models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Textual Notes'),
        ),
        migrations.AddField(
            model_name='events',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='events',
            name='day',
            field=models.DateField(auto_now_add=True),
        ),
    ]
