# Generated by Django 3.1.2 on 2020-11-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
