# Generated by Django 3.1.2 on 2020-11-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0002_addon_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='user',
        ),
    ]
