# Generated by Django 3.1.2 on 2020-11-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='', max_length=255)),
                ('price', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='menu/')),
            ],
        ),
    ]
