# Generated by Django 3.1.2 on 2020-11-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entree', models.CharField(default='', max_length=255)),
                ('price', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='menu/')),
            ],
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
