# Generated by Django 3.1.2 on 2020-11-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20201104_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
