# Generated by Django 3.1.2 on 2020-11-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20201110_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='addon_choices',
            field=models.CharField(blank=True, choices=[('Protein', 'Protein'), ('Veggies', 'Veggies'), ('High Carbs', 'High Carbs')], max_length=255),
        ),
    ]
