# Generated by Django 3.1.2 on 2020-11-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_addon_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addon',
            old_name='addon_choices',
            new_name='category',
        ),
    ]
