# Generated by Django 3.1.2 on 2020-11-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20201111_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='checkbox',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='checkbox',
            field=models.CharField(default='', max_length=255),
        ),
    ]
